from pathlib import Path

path = Path("bot.py")
text = path.read_text(encoding="utf-8")

text = text.replace("from datetime import date, datetime", "from datetime import UTC, date, datetime")
text = text.replace(
    "return datetime.utcnow().isoformat(timespec=\"seconds\")",
    "return datetime.now(UTC).isoformat(timespec=\"seconds\")",
)

helpers = '''\n\ndef item_search_text(item: sqlite3.Row) -> str:\n    return normalize(\n        " ".join(\n            [\n                item["dish_name"] or "",\n                item["ingredients"] or "",\n                item["allergens"] or "",\n                item["tags"] or "",\n            ]\n        )\n    )\n\n\ndef restriction_conflict(restriction: str, item: sqlite3.Row) -> str | None:\n    text = item_search_text(item)\n    for safe_phrase in ("sem gluten", "sem lactose", "sem carne", "vegetariano", "vegetariana", "vegano", "vegana"):\n        text = text.replace(safe_phrase, "")\n    restriction_key = normalize(restriction)\n    checks = {\n        "sem gluten": (("gluten", "trigo", "farinha"), "contem gluten"),\n        "sem lactose": (("lactose", "leite", "queijo", "creme", "manteiga"), "contem lactose ou derivados de leite"),\n        "vegetariana": (("carne", "frango", "peixe", "bovina", "suina", "porco", "camarao"), "nao esta marcado como vegetariano"),\n        "sem frutos do mar": (("peixe", "camarao", "frutos do mar", "marisco"), "contem peixe ou frutos do mar"),\n    }\n    for key, (terms, reason) in checks.items():\n        if key in restriction_key and any(term in text for term in terms):\n            return reason\n    return None\n\n\ndef compatible_menu_items(restriction: str) -> list[sqlite3.Row]:\n    return [item for item in list_menu_items() if not restriction_conflict(restriction, item)]\n\n\ndef recommend_item(telegram_id: int | None, restriction: str) -> sqlite3.Row | None:\n    compatible = compatible_menu_items(restriction)\n    if not compatible:\n        return None\n    compatible_by_key = {item["dish_key"]: item for item in compatible}\n    if telegram_id:\n        for row in top_dishes(telegram_id, 10):\n            if row["dish_key"] in compatible_by_key:\n                return compatible_by_key[row["dish_key"]]\n    return compatible[0]\n'''

if "def restriction_conflict(" not in text:
    marker = '''def get_dish_name(key: str) -> str:\n    item = load_menu_item(key)\n    return item["dish_name"] if item else DEFAULT_DISHES.get(key, key.replace("_", " ").title())\n'''
    text = text.replace(marker, marker + helpers)

text = text.replace(
    "SELECT dish_name, ordered_at FROM orders WHERE telegram_id = ? ORDER BY ordered_at DESC LIMIT ?",
    "SELECT dish_key, dish_name, ordered_at FROM orders WHERE telegram_id = ? ORDER BY ordered_at DESC LIMIT ?",
)

start = text.index("def menu_payload(")
end = text.index("\ndef order_payload", start)
text = text[:start] + '''def menu_payload(day: str | None = None, restriction: str = "") -> dict:\n    items = list_menu_items(day)\n    if not items:\n        return {"text": "\\U0001f614 Ainda nao temos pratos disponiveis para esse dia.", "buttons": [[("\\U0001f957 Ver cardapio completo", "menu_today")]]}\n    lines = ["\\U0001f957 <b>Cardapio disponivel:</b>"]\n    buttons = []\n    for item in items:\n        tags = f" - {escape(item['tags'])}" if item["tags"] else ""\n        allergens = f"\\nAlergenicos: {escape(item['allergens'])}" if item["allergens"] else ""\n        conflict = restriction_conflict(restriction, item) if restriction else None\n        safety = f"\\n\\U0001f6a0 Atencao: {escape(conflict)}" if conflict else "\\n\\u2705 Compativel com seu cadastro"\n        lines.append(\n            f"<b>{escape(item['dish_name'])}</b> - {format_price(item['price_cents'])}\\n"\n            f"Dia: {escape(item['day_of_week'])}{tags}{allergens}{safety}"\n        )\n        buttons.append([(f"\\U0001f37d Pedir {item['dish_name'][:30]}", f"dish:{item['dish_key']}")])\n    return {"text": "\\n\\n".join(lines), "buttons": buttons}\n\n''' + text[end+1:]

payloads = '''\n\ndef safety_warning_payload(item: sqlite3.Row, restriction: str, reason: str) -> dict:\n    alternatives = compatible_menu_items(restriction)\n    buttons = [[(f"\\U0001f957 Pedir {alt['dish_name'][:28]}", f"dish:{alt['dish_key']}")] for alt in alternatives[:3]]\n    buttons.append([("\\U0001f957 Ver cardapio", "menu_today"), ("\\U0001f464 Meu perfil", "profile")])\n    return {\n        "text": (\n            "\\u26a0\\ufe0f <b>Antes de confirmar, preciso te avisar:</b>\\n\\n"\n            f"O prato <b>{escape(item['dish_name'])}</b> {escape(reason)} e pode nao combinar com sua restricao cadastrada: "\n            f"<b>{escape(restriction)}</b>.\\n\\n"\n            "Por seguranca, nao registrei esse pedido. Separei algumas opcoes mais adequadas para voce \\U0001f33f"\n        ),\n        "buttons": buttons,\n    }\n\n\ndef recommendation_payload(context: ContextTypes.DEFAULT_TYPE) -> dict:\n    data = profile(context)\n    item = recommend_item(data.get("telegram_id"), data.get("restriction", ""))\n    if not item:\n        return {\n            "text": (\n                "\\U0001f614 Ainda nao encontrei uma recomendacao segura com o cardapio atual.\\n\\n"\n                "Posso te mostrar o cardapio completo para voce escolher com calma?"\n            ),\n            "buttons": [[("\\U0001f957 Ver cardapio", "menu_today"), ("\\U0001f464 Meu perfil", "profile")]],\n        }\n    recent_keys = {row["dish_key"] for row in recent_orders(data.get("telegram_id"), 10)} if data.get("telegram_id") else set()\n    reason = "ele combina com seu cadastro"\n    if item["dish_key"] in recent_keys:\n        reason = "voce ja pediu antes e ele continua compativel com seu cadastro"\n    elif item["tags"]:\n        reason = f"ele tem perfil {escape(item['tags'])} e respeita seu cadastro"\n    return {\n        "text": (\n            "\\u2b50 <b>Minha recomendacao para hoje:</b>\\n\\n"\n            f"<b>{escape(item['dish_name'])}</b> - {format_price(item['price_cents'])}\\n"\n            f"Escolhi porque {reason} \\U0001f33f"\n        ),\n        "buttons": [[(f"\\U0001f37d Pedir {item['dish_name'][:30]}", f"dish:{item['dish_key']}")], [("\\U0001f957 Ver cardapio", "menu_today")]],\n    }\n'''

if "def safety_warning_payload(" not in text:
    text = text.replace("\ndef profile_payload", payloads + "\ndef profile_payload")

text = text.replace("await send_payload(update, menu_payload(), context)", "await send_payload(update, menu_payload(restriction=profile(context).get(\"restriction\", \"\")), context)")
text = text.replace("await send_payload(update, menu_payload(), context, edit=True)", "await send_payload(update, menu_payload(restriction=profile(context).get(\"restriction\", \"\")), context, edit=True)")

old_callback = '''    if data.startswith("dish:"):\n        if not registered(context):\n            await ask_name(update, context, edit=True)\n            return\n        key = data.removeprefix("dish:")\n        user_id = tg_id(update)\n        if user_id:\n            record_order(user_id, key)\n            context.user_data["last_order"] = key\n        await send_payload(update, order_payload(key), context, edit=True)\n        return\n'''
new_callback = '''    if data.startswith("dish:"):\n        if not registered(context):\n            await ask_name(update, context, edit=True)\n            return\n        key = data.removeprefix("dish:")\n        user_id = tg_id(update)\n        item = load_menu_item(key)\n        if not item:\n            await send_payload(update, order_payload(key), context, edit=True)\n            return\n        conflict = restriction_conflict(profile(context).get("restriction", ""), item)\n        if conflict:\n            await send_payload(update, safety_warning_payload(item, profile(context).get("restriction", ""), conflict), context, edit=True)\n            return\n        if user_id:\n            record_order(user_id, key)\n            context.user_data["last_order"] = key\n        await send_payload(update, order_payload(key), context, edit=True)\n        return\n'''
text = text.replace(old_callback, new_callback)

old_recommend = '''    if data == "recommend":\n        await send_text(update, "\\u2b50 Minha sugestao de hoje e ver o cardapio disponivel e escolher uma opcao alinhada ao seu cadastro.", context, [[("\\U0001f957 Ver cardapio", "menu_today")]], edit=True)\n        return\n'''
new_recommend = '''    if data == "recommend":\n        if not registered(context):\n            await ask_name(update, context, edit=True)\n            return\n        await send_payload(update, recommendation_payload(context), context, edit=True)\n        return\n'''
text = text.replace(old_recommend, new_recommend)

old_message = '''    if item:\n        user_id = tg_id(update)\n        if user_id:\n            record_order(user_id, item["dish_key"])\n            context.user_data["last_order"] = item["dish_key"]\n        await send_payload(update, order_payload(item["dish_key"]), context)\n    elif "cardapio" in text or "tem hoje" in text or "o que tem" in text:\n        await send_payload(update, menu_payload(), context)\n    elif "perfil" in text or "cadastro" in text:\n'''
new_message = '''    if item:\n        user_id = tg_id(update)\n        conflict = restriction_conflict(profile(context).get("restriction", ""), item)\n        if conflict:\n            await send_payload(update, safety_warning_payload(item, profile(context).get("restriction", ""), conflict), context)\n            return\n        if user_id:\n            record_order(user_id, item["dish_key"])\n            context.user_data["last_order"] = item["dish_key"]\n        await send_payload(update, order_payload(item["dish_key"]), context)\n    elif "cardapio" in text or "tem hoje" in text or "o que tem" in text:\n        await send_payload(update, menu_payload(restriction=profile(context).get("restriction", "")), context)\n    elif "recomenda" in text or "sugestao" in text or "sugestão" in text:\n        await send_payload(update, recommendation_payload(context), context)\n    elif "perfil" in text or "cadastro" in text:\n'''
text = text.replace(old_message, new_message)

path.write_text(text, encoding="utf-8")
print("bot.py sincronizado. Rode: python -m unittest discover -s tests")
